name: shimmer
description: A package provides an easy way to add shimmer effect in Flutter project
version: 0.0.1
author: hunghd <hunghd.yb@gmail.com>
homepage: https://github.com/hnvn/flutter_shimmer

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: