name: shimmer
description: A package provides an easy way to add shimmer effect in Flutter project
version: 0.0.4
author: hunghd <hunghd.yb@gmail.com>
homepage: https://github.com/hnvn/flutter_shimmer

environment:
  sdk: '>=1.19.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: