name: shimmer
description: A package for shimmer effect
version: 0.0.1
author: hunghd
homepage:

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: